source "git@git.nevint.com:ios_dd/niopodrepo.git"
source "https://cdn.cocoapods.org/"
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, "13.0"

use_frameworks!
install! "cocoapods", :disable_input_output_paths => true

target 'IMModule_Example' do
pod'IMModule',:path=>'../'
pod'MPDebugTools',"1.4.3",:subspecs=>["CN"]
pod"IMUI","0.3.34"
pod"MPBusinessComponent/CN","0.14.16"
pod"MPBusinessModel","0.11.17",:subspecs=>["Vehicle","CNLink","CNAccount","Review","AntiFraud","AddressBookCN","CNPOI","Invoice","APM","OCR","GlobalSearch"]
pod"NIOGray","1.0.3"
pod'NIOAppKit',"1.14.26"
pod'FDFoundation',:git=>"git@git.nioint.com:ios_dd/libraries/DOMOBILE-FeiDian/DOMOBILE-FeiDian-FDFoundation.git",:tag=>"1.3.13"
pod'NIOURLNavigator',:git=>"git@git.nioint.com:ios_dd/libraries/ios-libs/NIOURLNavigator.git",:tag=>"1.0.0"
  target 'IMModule_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|


      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '5.0'


      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
    installer.pods_project.build_configurations.each do |config|

        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
