source "git@git.nevint.com:ios_dd/niopodrepo.git"
source "https://cdn.cocoapods.org/"

use_frameworks!

platform :ios, "13.0"

target "NIOSocial_Example" do
pod'LookinServer'
,configurations=>['Debug']
,"1.2.433"
pod"MPDebugTools"
pod"NIOApiProviders"
pod"MPUIKit",subspecs=>["NIOUIKitDeprecated","ALLSubSpecs"],"8.8.8"
pod"MPBusinessModel",subspecs=>["Vehicle","CNLink","CNAccount","Review","AntiFraud"],"0.11.15"
pod"MPRouter","1.3.6"
pod"MPApi","0.2.12"
pod"MPBusinessComponent/CN","0.14.11"
pod"MPSwiftUI",:git=>"git@git.nioint.com:ios_dd/mpswiftui.git",:tag=>"1.0.2"
pod"MPLog","2.0.3"
pod"MPLocale","0.5.0"
pod"MPFoundation",:git=>"git@git.nioint.com:ios_dd/mpfoundation.git",:tag=>"0.3.8"

pod"MPCache","0.4.16"



pod'MPPermissions',subspecs=>['CCRC','Network','Location','PhotoLibrary','Camera','Notification','Microphone','Biometrics','Bluetooth','Calendar','MPAuthorisationManager'],"1.0.15"
pod'Eureka',:git=>"git@git.nioint.com:ios_dd/libraries/ios-libs/Eureka.git",:tag=>"4.3.2"
pod"SDWebImage","5.15.4"
pod"MJRefresh","3.1.15.1"
pod'RxCocoa',"5.1.1"
pod'SnapKit',"5.0.1"
pod'SwiftyJSON',"4.3.0"
pod"lottie-ios","3.2.1"
pod"MPHybrid/CN","0.4.77"
pod"NIONetKit",:git=>"git@git.nioint.com:ios_dd/libraries/ios/nio-net-kit.git",:tag=>"2.0.0"
pod"NIOAggregationLib",:git=>"git@git.nioint.com:ios-libs/nioaggregationlib.git",:tag=>"1.0.2"
pod"NIOAppKit","1.14.26"
pod"NIOQMap3D","1.0.2"
pod"NIOPOISearch","0.6.13"
 pod "NIOPhotoPicker", :git => "git@git.nevint.com:ios_dd/libraries/ios-libs/NIOHXPhotoPicker.git", :tag => "nio_1.2.3"
 pod "NIOSocial", :path => "../"
end

post_install do |installer|
 installer.pods_project.build_configurations.each do |config|
 config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)', '-D DEMO']
 end

 installer.pods_project.targets.each do |target|
 target.build_configurations.each do |config|
 # 移除 iOS 8.0 部署配置。Xcode 12 已不支持 iOS 8.0，移除设置将清理编译器警告。
 # Pods 项目将使用主项目部署配置。
 config.build_settings.delete "IPHONEOS_DEPLOYMENT_TARGET"

 config.build_settings["ENABLE_BITCODE"] = "NO"
 end
 end
end
